import Cookie from './cookie';
import debounce from './debounce';
import getter from './getter';
import math from './math';
import singleton from './singleton';
import throttle from './throttle';
import type from './type';
import rule from './rule';
import validator from './validator';
import proxy from './proxy';
import currying from './currying';
import { compose, pipe } from './compose';
export { Cookie, compose, currying, debounce, getter, math, singleton, throttle, type, rule, validator, proxy, pipe };